package com.testpilot.model;

import java.util.List;

/**
 * Model class representing a single generated test case.
 * Coincides with the JSON structure generated by the LLM.
 */
public class TestCase {
    /** Unique identifier for the test case (e.g., Testcase-001) */
    public String id;
    /** The high-level scenario being tested */
    public String scenario;
    /** Short descriptive title for the test case */
    public String title;
    /** List of requirements or states that must be met before execution */
    public List<String> preconditions;
    /** Step-by-step instructions for performing the test */
    public List<String> steps;
    /** The outcome that indicates a successful test */
    public String expectedResult;

    /** @return The ID of this test case. */
    public String getId() {
        return id;
    }

    /** @param id The unique ID to set for this test case. */
    public void setId(String id) {
        this.id = id;
    }
}
